name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  all-is-okey:
    name: Deploy
    runs-on: "ubuntu-latest"
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Firebase CLI
      run: npm install -g firebase-tools@latest

    - name: Select Project for Deploy
      run: firebase use default --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

    - name: Deploy Firestore rules to Production
      run: firebase deploy --only firestore:rules --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

    - name: Deploy Storage rules to Production
      run: firebase deploy --only storage --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

    - name: Deploy Functions to Production
      run: firebase deploy --only functions --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
